    <div class="wrapper2">

        <form class="form-signin2" method="POST" action="/autenticar">
            <div class="form-group">
            <img src="/img/logo-nexa-1.png" class="img" width='250px'  alt="Cinque Terre">

            </div>   
            <div class="form-group">

                <label for="exampleInputEmail1">Usuário</label>
                <input type="text" name="matricula" class="form-control" id="" aria-describedby="emailHelp" placeholder="Digite seu usuário">
              </div>
              <div class="form-group">
                <label for="exampleInputPassword1">Senha</label>
                <input type="password" name="senha" class="form-control" id="" placeholder="Senha">
              </div>
              <?php if($this->view->login == 'erro'){?>
              <div class ="row">
                <div class="col">
                  <span class="text text-danger" id="erro_login"> Usuário ou senha incorretos </span>
                </div>
              </div>          
              <?php }?>
              <div class="d-flex justify-content-center">
              <button type="submit" class="btn btn-primary">Entrar</button>
              </div>
        </form>
      </div>