
    <div class="container-fluid bg-light">
        <div class="row bg-">
            <!-- <div class="col-4"></div> -->
            <div class="col-12">
                <h1 class="text-center ">APONTA NEXA<h1>
            </div>
            <!-- <div class="col-2"></div> -->

        </div>

        <div class="row">
            <div class="col-4"></div>
            <div class="col-7">
            <ul class="nav nav-pills">
                <li class="nav-item">
                    <a aria-selected="true" class="nav-link active" data-toggle="tab" href="#home" >Chamado</a>
                </li>
                <!-- <li><a data-toggle="tab" href="#menu1">Menu 1</a></li> -->
                <li>
                    <a aria-selected="false" class="nav-link " data-toggle="tab" href="#menu2">atividades</a>
                </li>
                <li>
                <a aria-selected="false" class="nav-link " data-toggle="tab" href="#menu3">Meu dia</a>
                </li>
            </ul>
                        
            </div>
        </div>

<div class="tab-content">
    <div id="home" class="tab-pane fade show active">
        <div class="row  bg-light">
                <div class="col-1"></div>
                <!-- inicio div direita -->
                <div class="col-10 card">

                    <h5 class="card-title text-center ">Chamado</h5>

                    <form name="insereApontamento" onsubmit="javascript:return ValidaFormInsert(this);" method="POST" action="/apontamento/criaApontamento">
                        <div class="form-row">
                            <div class="form-group col-lg-2"></div>
                            <div class="form-group col-lg-4">
                                <label for="inputState">Cliente</label>
                                <select id="cliente" name="cliente" class="form-control bg-light" required>
                                <option value="" disabled selected>Selecione o cliente </option>
                                <?php foreach($this->view->clientes as $cliente ){?>
                                    <option value="<?php echo $cliente['id'] ?>"> <?php echo $cliente['nome']; ?> </option>
                            <?php };?>     
                                </select>
                            </div>
                            <div class="form-group col-lg-4">
                                <label for="inputState">Contrato</label>
                                <select id="contrato" name="contrato" class="form-control bg-light" required>
                                <!-- <option value="erro">escolha um contrato</option> -->
                                <option value="" disabled selected>Selecione o campo interior</option>

                                </select>
                            </div>

                            <div class="form-group col-lg-2"></div>

                        </div>


                        <div class="form-row">
                            <div class="form-group col-md-4 ">
                                <label for="">N° chamado</label>
                                <input type="" name="numero_chamado" id="numero_chamado" class="form-control bg-light" required   placeholder="numerochamado" >
                            </div>
                            <div class="form-group col-md-4">
                                <label for="inputState">Tipo de atividade</label>
                                <select id="tipo_atividade" name="Tipo_atividade" class="form-control bg-light" required>
                                <option value="" disabled selected>tipo de atividade</option>

                                <?php foreach($this->view->tipoAtividade as $tp_atividade ){?>
                                    <option value="<?php echo $tp_atividade['id'] ?>"> <?php echo $tp_atividade['tipo_atividade']; ?> </option>
                            <?php };?>
                                </select>
                            </div>
                            <div class="form-group col-md-4">
                                <label for="inputState">Atividade</label>
                                <select id="atividade" name="atividade" class="form-control bg-light" required>
                                <!-- <option>escolha um tipo de atividade</option> -->
                                <option value="" disabled selected>Selecione o campo anterior</option>


                                </select>
                            </div>

                        </div>

                        <div class="form-row">
                            <div class="form-group col-sm-2">
                                <label for="">Data inicial</label>
                                <input type="date" name="data_inicial" class="form-control bg-light" id="data_inicial" value =<?php echo "\"".date('Y-m-d')."\"" ;?>  required>
                            </div>                    
                            <div class="form-group col-sm-2">
                                <label for="">Hora inicial</label>
                                <input type="time" name="hora_inicial" class="form-control bg-light" id="hora_inicial"  value =<?php echo "\"".date('H:i')."\"" ;?> required>
                            </div>
                            <!-- <div class="form-group col-sm-4">
                                <label for="">data inicial</label>
                                <input type="datetime-local" name="data_inicial" class="form-control bg-light" id="data_inicial" placeholder="data inicial" required>
                            </div> -->
                            <div class="form-group col-sm-2">
                                <label for="">Data final</label>
                            <input type="date" name="data_final" class="form-control bg-light" id="data_final" value =<?php echo "\"".date('Y-m-d')."\"" ;?> required>
                            </div>                    
                            <div class="form-group col-sm-2">
                                <label for="">Hora final</label>
                                <input type="time" name="hora_final" class="form-control bg-light" id="hora_final" value =<?php echo "\"".date('H:i')."\"" ;?> required>
                            </div>
                            <!-- <div class="form-group col-sm-4">
                                <label for="">data final</label>
                                <input type="datetime-local" name="data_final" class="form-control bg-light" id="data_final" placeholder="data final" required>
                            </div> -->
                            <div class="form-group col-sm-4">
                                <label for="inputState">Tipo de hora</label>
                                <select id="" name="tipo_hora" class="form-control bg-light" required>
                                <?php foreach($this->view->tipo_hora as $tp_hora ){?>
                                    <option value="<?php echo $tp_hora['id'] ?>"> <?php echo $tp_hora['tipo_hora']; ?> </option>
                            <?php };?>
                                </select>
                            </div>
                        </div>
    <!-- 
                        <?php //if($this->view->dataInvalida == "erroCadastro"){?>
                        <div class ="row">
                        <div class="col-6"></div>
                            <div class="col-3"  style="align = center">
                            <h6 class="text text-danger" > Intervalo de data invalido,teste novamente</h6>
                            </div>
                        </div>          
                    <?php// }?> -->
                    <div class="row">
                    <div class="col-5" ></div>
                        <div class="col-4">
                            <div id="alert_erro" class="text text-danger" style="align = center">  </div>
                        </div>
                    <div class="col-2" ></div>
                    </div>
                    <div class="row">
                    <div class="col-4" ></div>
                        <div class="col-6 ">
                        <label for="inputState">Descrição da atividade</label>
                        <textarea class="d-flex justify-content-center" name="descricao" id="descricao" cols="60" rows="5" required ></textarea>
                        </div>
                    <div class="col-2" ></div>
                    </div>
                        <div class="form-row">
                            <div class="form-group col-4"></div>
                            <div class="form-group col-5">
                                <input class="btn bg-info text-white" type="submit" value="cadastrar">
                            </div>
                            <div class="form-group col-3"></div>

                        </div>
                    </form>
                </div><!-- fim  div meio -->
                <div class="col-1"></div>
            </div>
            <div class="row" style="overflow: auto; width: 100%; height: 400px; ">
            <!-- inicio div esquerda -->
            <!-- <div class="col-1"></div> -->
            <div class="col-12  ">
                <table class="table table-bordered table-striped" id="tabela_apontamentos" name="tabela_apontamentos">
                    <thead>
                        <tr id="1" >
                            <th class="th-sm">N° chamado
                            </th>
                            <th class="th-sm">cliente
                            </th>
                            <th class="th-sm">Tipo Atividade
                            </th>
                            <th class="th-sm">Atividade
                            </th>
                            <th class="th-sm">Data inicial
                            </th>
                            <th class="th-sm">Data final
                            </th>
                            <th class="th-sm">Tipo de hora
                            </th>
                            <th class="th-sm">Duracão
                            </th>
                            <th class="th-sm">
                            </th>


                        </tr >
                    </thead>
                    <tbody>
                        <?php foreach($this->view->apontamentosRecentes as $apontamento){?>
                        <tr <?php if($apontamento['FK_status_Id']=='1'){ echo "class=bg-info";} ?> >
                        <td style="display:none;" > <?php echo $apontamento['Id'];?> </td>
                            
                            <td  > <?php echo $apontamento['num_chamado']; ?> </td>
                            <td><?php echo $apontamento['cliente']; ?></td>
                            <td><?php echo $apontamento['tipo_atividade']; ?></td>
                            <td> <?php echo $apontamento['atividade']; ?></td>
                            <td><?php echo $apontamento['Data_inicial']; ?></td>
                            <td><?php echo $apontamento['Data_final']; ?></td>
                            <td><?php echo $apontamento['tipo_hora']; ?></td>
                            <td> <?php echo $apontamento['duracao']; ?></td>
                            <td style="text-align:center;">
                                <button class="btn-sm btn-success" data-toggle="modal" data-target="#myModal"
                                    contenteditable="false">Editar</button>
                            </td>
                        </tr>
                        <?php } ?>
                    </tbody>
                    <tfoot>
                        <tr>
                            <th class="th-sm">N° chamado
                            </th>
                            <th class="th-sm">cliente
                            </th>
                            <th class="th-sm">Tipo Atividade
                            </th>
                            <th class="th-sm">Atividade
                            </th>
                            <th class="th-sm">Data inicial
                            </th>
                            <th class="th-sm">Data final
                            </th>
                            <th class="th-sm">Tipo de hora
                            </th>
                            <th class="th-sm">Duracão
                            </th>
                            <th class="th-sm">editar
                            </th>

                        </tr>
                    </tfoot>
                </table>
            </div>
            <!-- <div class="col-1"></div> -->

        </div><!-- fim  div direita --> 
    </div>
    <div id="menu2" class="tab-pane fade">
    <div class="row  bg-light">
                <div class="col-2"></div>
                <!-- inicio div direita -->
                <div class="col-7 card">

                    <h5 class="card-title text-center ">Atividade</h5>

                    <form name="insereApontamento" onsubmit="javascript:return ValidaFormInsert(this);" method="POST" action="/apontamento/criaApontamento">
                        <div class="form-row">
                            <div class="form-group col-lg-1"></div>
                            <div class="form-group col-lg-5">
                                <label for="inputState">Cliente</label>
                                <select id="cliente" name="cliente" class="form-control bg-light" required>
                                <option value="" disabled selected>Selecione o cliente </option>
                                <?php foreach($this->view->clientes as $cliente ){?>
                                    <option value="<?php echo $cliente['id'] ?>"> <?php echo $cliente['nome']; ?> </option>
                            <?php };?>     
                                </select>
                            </div>
                            <div class="form-group col-lg-5">
                                <label for="inputState">Contrato</label>
                                <select id="contrato" name="contrato" class="form-control bg-light" required>
                                <!-- <option value="erro">escolha um contrato</option> -->
                                <option value="" disabled selected>Selecione o campo interior</option>

                                </select>
                            </div>

                            <!-- <div class="form-group col-lg-2"></div> -->
  

  <!-- e -->
                        </div>


                        <div class="form-row">
                        <div class="form-group col-lg-1"></div>

                        <div class="form-group col-sm-5">
                                <label for="inputState">Tipo de apontamento</label>
                                <select id="" name="tipo_hora" class="form-control bg-light" required>
                                    <option>Reunião</option>
                                    <option>Pausa</option>
                                    <option>Atendimento emergencial</option>
                                    <option>Apoio informativo</option>
                                    <option>5</option>
                                </select>
                            </div>

                        <div class="form-group col-sm-5">
                                <label for="inputState">Tipo de hora</label>
                                <select id="" name="tipo_hora" class="form-control bg-light" required>
                                <?php foreach($this->view->tipo_hora as $tp_hora ){?>
                                    <option value="<?php echo $tp_hora['id'] ?>"> <?php echo $tp_hora['tipo_hora']; ?> </option>
                            <?php };?>
                                </select>
                            </div>
                        </div>

                        <div class="form-row">
                        <!-- <div class="form-group col-lg-1"></div> -->

                            <div class="form-group col-sm-3">
                                <label for="">Data inicial</label>
                                <input type="date" name="data_inicial" class="form-control bg-light" id="data_inicial" value =<?php echo "\"".date('Y-m-d')."\"" ;?>  required>
                            </div>                    
                            <div class="form-group col-sm-3">
                                <label for="">Hora inicial</label>
                                <input type="time" name="hora_inicial" class="form-control bg-light" id="hora_inicial"  value =<?php echo "\"".date('H:i')."\"" ;?> required>
                            </div>
                            <!-- <div class="form-group col-sm-4">
                                <label for="">data inicial</label>
                                <input type="datetime-local" name="data_inicial" class="form-control bg-light" id="data_inicial" placeholder="data inicial" required>
                            </div> -->
                            <!-- <div class="form-group col-lg-1"></div> -->

                            <div class="form-group col-sm-3">
                                <label for="">Data final</label>
                            <input type="date" name="data_final" class="form-control bg-light" id="data_final" value =<?php echo "\"".date('Y-m-d')."\"" ;?> required>
                            </div>                    
                            <div class="form-group col-sm-3">
                                <label for="">Hora final</label>
                                <input type="time" name="hora_final" class="form-control bg-light" id="hora_final" value =<?php echo "\"".date('H:i')."\"" ;?> required>
                            </div>
                            <!-- <div class="form-group col-sm-4">
                                <label for="">data final</label>
                                <input type="datetime-local" name="data_final" class="form-control bg-light" id="data_final" placeholder="data final" required>
                            </div> -->

                        </div>
    <!-- 
                        <?php //if($this->view->dataInvalida == "erroCadastro"){?>
                        <div class ="row">
                        <div class="col-6"></div>
                            <div class="col-3"  style="align = center">
                            <h6 class="text text-danger" > Intervalo de data invalido,teste novamente</h6>
                            </div>
                        </div>          
                    <?php// }?> -->
                    <div class="row">
                    <div class="col-5" ></div>
                        <div class="col-4">
                            <div id="alert_erro" class="text text-danger" style="align = center">  </div>
                        </div>
                    <div class="col-2" ></div>
                    </div>
                    <div class="row">
                        <div class="col-3" ></div>
                            <div class="col-6 ">
                            <label for="inputState">Descrição da atividade</label>
                            <textarea class="d-flex justify-content-center" name="descricao" id="descricao" cols="60" rows="5" required ></textarea>
                            </div>
                        <div class="col-2" ></div>
                    </div>
                        <div class="form-row">
                            <div class="form-group col-3"></div>
                            <div class="form-group col-5">
                                <input class="btn bg-info text-white" type="submit" value="cadastrar">
                            </div>
                            <div class="form-group col-3"></div>

                        </div>
                    </form>
                </div><!-- fim  div meio -->
                <div class="col-2"></div>
            </div>
    </div>
    <div id="menu3" class="tab-pane fade">  


    <div class="row">
            <div class="col-2"></div>
            <div class="col-7">
               
                <div class="card">
                    <div class="card-header">
                        MEU DIA
                    </div>
                    <div class="card-body">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                <th scope="col">ordem</th>
                                <th scope="col">chamado / ID</th>
                                <th scope="col">tipo</th>
                                <th scope="col">inicio</th>
                                <th scope="col">fim</th>
                                <th scope="col">duração</th>

                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <th scope="row">1</th>
                                    <td>278954</td>
                                    <td>chamado</td>
                                    <td>2020-04-27 14:33:00</td>
                                    <td>2020-04-27 14:33:00</td>
                                    <td>60</td>
                                </tr>
                                <tr>
                                    <th scope="row">2</th>
                                    <td>278954</td>
                                    <td>chamado</td>
                                    <td>2020-04-27 14:33:00</td>
                                    <td>2020-04-27 14:33:00</td>
                                    <td>60</td>
                                </tr>
                                <tr>
                                    <th scope="row">3</th>
                                    <td>278954</td>
                                    <td>chamado</td>
                                    <td>2020-04-27 14:33:00</td>
                                    <td>2020-04-27 14:33:00</td>
                                    <td>60</td>
                                </tr>
                                <tr>
                                    <th scope="row">4</th>
                                    <td>278954</td>
                                    <td>chamado</td>
                                    <td>2020-04-27 14:33:00</td>
                                    <td>2020-04-27 14:33:00</td>
                                    <td>60</td>
                                </tr>
                                <tr>
                                    <th scope="row">5</th>
                                    <td>147</td>
                                    <td>reunião</td>
                                    <td>2020-04-27 14:33:00</td>
                                    <td>2020-04-27 14:33:00</td>
                                    <td>60</td>
                                </tr>
                            </tbody>
                            <tfoot>
                        <tr>
                            <th class="th-sm">
                            </th>
                            <th class="th-sm">
                            </th>
                            <th class="th-sm">
                            </th>
                            <th class="th-sm">
                            </th>
                            <th class="th-sm">
                            </th>
                            <th class="th-sm">8 horas
                            </th>
 

                        </tr>
                    </tfoot>
                        </table>
                    </div>
                </div>
                        
            </div>
        </div>





    </div>
    <!-- fim menu3 -->
  </div>
































<!-- MODAL DO APONTAMENTO DE CHAMADO -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content"></div>
        </div>
        <div class="modal-dialog">
            <div class="modal-content"></div>
        </div>
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"> <span aria-hidden="true" class="">×
                        </span><span class="sr-only">Fechar</span>

                    </button>
                    <h4 class="modal-title" id="myModalLabel">Editar apontamento</h4>

                </div>
                <div class="modal-body">
                    <form name="edita_isso" id= "edita_isso" method="POST" action="/apontamento/alterarApotamento">
                        <div class="form-row">
                            <div class="form-group col-lg-3">
                            <input type=hidden id="id_linha_edita" name="id_linha_edita">
                            </div>
                            <div class="form-group col-lg-6">
                                <label for="inputState">Cliente</label>
                                <select id="edita_cliente" name="edita_cliente" class="form-control bg-light">
                                    <?php foreach($this->view->clientes as $cliente ){?>
                                        <option value="<?php echo $cliente['id'] ?>"> <?php echo $cliente['nome']; ?> </option>
                                   <?php };?>  
                                </select>
                            </div>

                        </div>
                        <div class="form-row">
                                <div class="form-group col-lg-6">
                                <label for="inputState">Contrato</label>
                                <select id="edita_contrato" name="edita_contrato" class="form-control bg-light">
                                </select>
                              </div>

                            <div class="form-group col-lg-6">
                                <label for="">N° chamado</label>
                                <input type="text" class="form-control bg-light" id="edita_num_chamado" name="edita_num_chamado" placeholder="numero chamado">
                            </div>

                        </div>

                        <div class="form-row">
                            <div class="form-group col-lg-6">
                                <label for="inputState">Tipo de atividade</label>
                                <select id="edita_tp_atv" name="edita_tp_atv" class="form-control bg-light">
                           <?php foreach($this->view->tipoAtividade as $tp_atividade ){?>
                                <option value="<?php echo $tp_atividade['id'] ?>"> <?php echo $tp_atividade['tipo_atividade']; ?> </option>
                           <?php }?>
                                </select>
                            </div>
                            <div class="form-group col-lg-6">
                                <label for="inputState"> Atividade</label>
                                <select id="edita_atividade" name="edita_atividade" class="form-control bg-light">
                                </select>
                            </div>
                        </div>
                        
                        <div class="form-row">
                            <div class="form-group col-lg-6">
                                <label for="inputState">Data inicial</label>
                                <input type="date" class="form-control bg-light" id="edita_dt_ini" name="edita_dt_ini" placeholder="data inicial">
                            </div>
                            <div class="form-group col-lg-6">
                                <label for="inputState">Hora inicial</label>
                                <input type="time" class="form-control bg-light" id="edita_time_ini" name="edita_time_ini" placeholder="data inicial">
                            </div>
                        </div>
                        <div class="form-row">

                            <div class="form-group col-lg-6">
                                <label for="inputState"> Data final</label>
                                <input type="date" class="form-control bg-light" id="edita_dt_fim" name="edita_dt_fim" placeholder="data inicial">
                            </div>
                            <div class="form-group col-lg-6">
                                <label for="inputState"> Hora final</label>
                                <input type="time" class="form-control bg-light" id="edita_time_fim" name="edita_time_fim" placeholder="data inicial">
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-lg-3"> </div>
                            
                            <div class="form-group col-lg-6">
                                <label for="inputState">Tipo de hora</label>
                                <select id="edita_tp_hr" name="edita_tp_hr" class="form-control bg-light">
                                    <?php foreach($this->view->tipo_hora as $tp_hora ){?>
                                        <option value="<?php echo $tp_hora['id'] ?>"> <?php echo $tp_hora['tipo_hora']; ?> </option>
                                   <?php };?>
                                </select>
                            </div>
                        </div>
                        <span id="erro_edita" name="erro_edita" class="text-danger"></span>
                    </form>


                </div>
                <div class="modal-footer">
                    <button type="button" class="btn-sm btn-default" data-dismiss="modal">Fechar</button>
                    <button type="button" class="btn-sm btn-primary">Salvar</button>
                    <button type="button" class="btn-sm btn-danger" id="exclui_apontamento">Excluir</button>

                </div>
            </div>
        </div>
    </div>





    <!-- FIM DO CONTAINER DA TELA  -->
    </div>
     <script type="text/javascript" charset="utf8" src="/js/scripts.js"></script>
