
    <div class="container-fluid bg-light">
        <div class="row bg-">
            <!-- <div class="col-4"></div> -->
            <div class="col-12">
                <h1 class="text-center ">Aponta NEXA<h1>
            </div>
            <!-- <div class="col-2"></div> -->

        </div>


        <div class="row  bg-light">
            <div class="col-1"></div>
            <!-- inicio div direita -->
            <div class="col-10 card">

                <h5 class="card-title text-center ">Apontamento de hora</h5>

                <form name="insereApontamento" method="POST" action="/apontamento/criaApontamento">
                    <div class="form-row">
                        <div class="form-group col-lg-2"></div>
                        <div class="form-group col-lg-4">
                            <label for="inputState">Cliente</label>
                            <select id="cliente" name="cliente" class="form-control bg-light">
                            <?php foreach($this->view->clientes as $cliente ){?>
                                <option value="<?php echo $cliente['id'] ?>"> <?php echo $cliente['nome']; ?> </option>
                           <?php };?>     
                            </select>
                        </div>
                        <div class="form-group col-lg-4">
                            <label for="inputState">Contrato</label>
                            <select id="contrato" name="contrato" class="form-control bg-light">
                            <option>escolha um contrato</option>
                            </select>
                        </div>

                        <div class="form-group col-lg-2"></div>

                    </div>


                    <div class="form-row">
                        <div class="form-group col-md-4 ">
                            <label for="">N° chamado</label>
                            <input type="" name="numero_chamado" class="form-control bg-light"  placeholder="numerochamado">
                        </div>
                        <div class="form-group col-md-4">
                            <label for="inputState">tipo de atividade</label>
                            <select id="tipo_atividade" name="tipo_atividade" class="form-control bg-light">
                            <?php foreach($this->view->tipoAtividade as $tp_atividade ){?>
                                <option value="<?php echo $tp_atividade['id'] ?>"> <?php echo $tp_atividade['tipo_atividade']; ?> </option>
                           <?php };?>
                            </select>
                        </div>
                        <div class="form-group col-md-4">
                            <label for="inputState">atividade</label>
                            <select id="atividade" name="atividade" class="form-control bg-light">
                            <option>escolha um tipo de atividade</option>

                            </select>
                        </div>

                    </div>

                    <div class="form-row">
                        <div class="form-group col-sm-4">
                            <label for="">data inicial</label>
                            <input type="datetime-local" name="data_inicial" class="form-control bg-light" id="data_inicial" placeholder="data inicial">
                        </div>
                        <div class="form-group col-sm-4">
                            <label for="">data final</label>
                            <input type="datetime-local" name="data_final" class="form-control bg-light" id="data_final" placeholder="data final">
                        </div>
                        <div class="form-group col-sm-4">
                            <label for="inputState">tipo de hora</label>
                            <select id="" name="tipo_hora" class="form-control bg-light">
                            <?php foreach($this->view->tipo_hora as $tp_hora ){?>
                                <option value="<?php echo $tp_hora['id'] ?>"> <?php echo $tp_hora['tipo_hora']; ?> </option>
                           <?php };?>
                            </select>
                        </div> 

                    

                    </div>
                    <div class="form-row">
                        <div class="form-group col-4"></div>
                        <div class="form-group col-5">
                            <input class="btn bg-info" type="submit" value="cadastrar">
                        </div>
                        <div class="form-group col-3"></div>

                    </div>
                </form>

            </div><!-- fim  div esquerda -->
            <div class="col-1"></div>

        </div>

        <div class="row" style="overflow: auto; width: 100%; height: 300px; ">
            <!-- inicio div esquerda -->
            <!-- <div class="col-1"></div> -->
            <div class="col-12  ">
                <table class="table table-bordered table-striped" id="tabela_apontamentos" name="tabela_apontamentos">
                    <thead>
                        <tr id="1" >
                            <th class="th-sm">N° chamado
                            </th>
                            <th class="th-sm">cliente
                            </th>
                            <th class="th-sm">Tipo Atividade
                            </th>
                            <th class="th-sm">Atividade
                            </th>
                            <th class="th-sm">Data inicial
                            </th>
                            <th class="th-sm">Data final
                            </th>
                            <th class="th-sm">Tipo de hora
                            </th>
                            <th class="th-sm">Duracão
                            </th>
                            <th class="th-sm">editar
                            </th>


                        </tr >
                    </thead>
                    <tbody>
                        <?php foreach($this->view->apontamentosRecentes as $apontamento){?>
                        <tr>
                        <td style="display:none;" > <?php echo $apontamento['Id']; ?> </td>
                            <td  > <?php echo $apontamento['num_chamado']; ?> </td>
                            <td><?php echo $apontamento['cliente']; ?></td>
                            <td><?php echo $apontamento['tipo_atividade']; ?></td>
                            <td> <?php echo $apontamento['atividade']; ?></td>
                            <td><?php echo $apontamento['Data_inicial']; ?></td>
                            <td><?php echo $apontamento['Data_final']; ?></td>
                            <td><?php echo $apontamento['tipo_hora']; ?></td>
                            <td> <?php echo $apontamento['duracao']; ?></td>
                            <td style="text-align:center;">
                                <button class="btn-sm btn-success" data-toggle="modal" data-target="#myModal"
                                    contenteditable="false">Edit</button>
                            </td>
                        </tr>
                        <?php } ?>
                    </tbody>
                    <tfoot>
                        <tr>
                            <th class="th-sm">N° chamado
                            </th>
                            <th class="th-sm">cliente
                            </th>
                            <th class="th-sm">Tipo Atividade
                            </th>
                            <th class="th-sm">Atividade
                            </th>
                            <th class="th-sm">Data inicial
                            </th>
                            <th class="th-sm">Data final
                            </th>
                            <th class="th-sm">Tipo de hora
                            </th>
                            <th class="th-sm">Duracão
                            </th>
                            <th class="th-sm">editar
                            </th>

                        </tr>
                    </tfoot>
                </table>
            </div>
            <!-- <div class="col-1"></div> -->

        </div><!-- fim  div direita -->
    </div>
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content"></div>
        </div>
        <div class="modal-dialog">
            <div class="modal-content"></div>
        </div>
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"> <span aria-hidden="true" class="">×
                        </span><span class="sr-only">Close</span>

                    </button>
                    <h4 class="modal-title" id="myModalLabel">editar apontamento</h4>

                </div>
                <div class="modal-body">
                    <form name="edita_isso" id= "edita_isso" method="POST" action="/apontamento/alterarApotamento">
                        <div class="form-row">
                            <div class="form-group col-lg-3">
                            <input type=hidden id="id_linha_edita" name="id_linha_edita">
                            </div>
                            <div class="form-group col-lg-6">
                                <label for="inputState">Cliente</label>
                                <select id="edita_cliente" name="edita_cliente" class="form-control bg-light">
                                    <?php foreach($this->view->clientes as $cliente ){?>
                                        <option value="<?php echo $cliente['id'] ?>"> <?php echo $cliente['nome']; ?> </option>
                                   <?php };?>  
                                </select>
                            </div>

                        </div>
                        <div class="form-row">
                                <div class="form-group col-lg-6">
                                <label for="inputState">Contrato</label>
                                <select id="edita_contrato" name="edita_contrato" class="form-control bg-light">
                                </select>
                              </div>

                            <div class="form-group col-lg-6">
                                <label for="">N° chamado</label>
                                <input type="text" class="form-control bg-light" id="edita_num_chamado" name="edita_num_chamado" placeholder="numero chamado">
                            </div>

                        </div>

                        <div class="form-row">
                            <div class="form-group col-lg-6">
                                <label for="inputState">tipo de atividade</label>
                                <select id="edita_tp_atv" name="edita_tp_atv" class="form-control bg-light">
                           <?php foreach($this->view->tipoAtividade as $tp_atividade ){?>
                                <option value="<?php echo $tp_atividade['id'] ?>"> <?php echo $tp_atividade['tipo_atividade']; ?> </option>
                           <?php }?>
                                </select>
                            </div>
                            <div class="form-group col-lg-6">
                                <label for="inputState"> atividade</label>
                                <select id="edita_atividade" name="edita_atividade" class="form-control bg-light">
                                </select>
                            </div>
                        </div>
                        
                        <div class="form-row">
                            <div class="form-group col-lg-6">
                                <label for="inputState">data inicial</label>
                                <input type="datetime-local" class="form-control bg-light" id="edita_dt_ini" name="edita_dt_ini" placeholder="data inicial">
                            </div>
                            <div class="form-group col-lg-6">
                                <label for="inputState"> data final</label>
                                <input type="datetime-local" class="form-control bg-light" id="edita_dt_fim" name="edita_dt_fim" placeholder="data inicial">
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-lg-3"> </div>
                            
                            <div class="form-group col-lg-6">
                                <label for="inputState">tipo de hora</label>
                                <select id="edita_tp_hr" name="edita_tp_hr" class="form-control bg-light">
                                    <?php foreach($this->view->tipo_hora as $tp_hora ){?>
                                        <option value="<?php echo $tp_hora['id'] ?>"> <?php echo $tp_hora['tipo_hora']; ?> </option>
                                   <?php };?>
                                </select>
                            </div>
                        </div>
                        <span id="erro_edita" name="erro_edita" class="text-danger"></span>
                    </form>


                </div>
                <div class="modal-footer">
                    <button type="button" class="btn-sm btn-default" data-dismiss="modal">Fechar</button>
                    <button type="button" class="btn-sm btn-primary">Salvar</button>
                    <button type="button" class="btn-sm btn-danger">Excluir</button>

                </div>
            </div>
        </div>
    </div>
    </div>
     <script type="text/javascript" charset="utf8" src="/js/scripts.js"></script>
