<div class="container " >
            <!-- Top Navigation -->

        <div>
        <h1 class="text-center text">Horas concluídas <h1>
        </div>            
			
			<div class="component">
				
				<table class="overflow-y">
					<thead>
						<tr>
                            <th>Funcionario</th>
                            <?php foreach($this->view->dataRange as $data) {?>
                                <th <?php if(in_array($data, $this->view->fds)){echo "class=bg-info"; } ?>   > 
                                <?php echo $data; 

                               //echo $data->format('w') % 6 ? 'Não é fim de semana' : 'é fim de semana';

                                ?> </th>
                            <?php } ?>
                            
						</tr>
					</thead>
					<tbody>
                    <?php foreach($this->view->resultadoMensal as $rmensal){?>
                                <tr>
  
                                  <?php  $cont = 0;
                                    //print_r($rmensal);
                                    foreach($rmensal as $dados){
                                        if(!$dados){
                                            ?> <td <?php if(in_array($cont - 1, $this->view->fds)){echo "class=bg-info dados_func"; } ?> >
                                                <?php echo 0; ?>
                                             </td> <?php
                                        }else{
                                            if($cont == 0){
                                                ?> <th hidden class="dados_func" >
                                                 <?php echo $dados ?>
                                                 </th> <?php
                                            }elseif($cont == 1){
                                                ?> 
                                                <th id="" class="dados_func" >
                                                 <?php echo $dados ?>
                                                 </th> 
                                                 <?php

                                            }else{
                                            ?> <td id="" <?php if(in_array($cont -1, $this->view->fds)){echo "class=bg-info dados_func"; } ?> > 
                                                <?php echo $dados ?></td>
                                             <?php
                                            }
                                        }
                                       // echo $cont;
                                        $cont ++;
                                    } //echo 'tamanho for:' . $cont . '</br>';
                              ?>
                              </tr>      
                           <?PHP }?>

                        
					</tbody>
				</table>
		
			</div>


		</div><!-- /container -->

        <div id="testem" >
                                </div>

<!-- <script type="text/javascript" charset="utf8" src="/js/scripts.js"></script> -->

<!-- Modal -->
<!-- Modal -->
<div class="modal fade" id="exampleModalScrollable" tabindex="-1" role="dialog" aria-labelledby="exampleModalScrollableTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-scrollable" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalScrollableTitle">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div id="testem" class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>