<!-- pagina com o total de horas dos  apontamentos concluidos  -->
<div class="container-fluid bg-light">
<div class="row">
        <div class="" >
            <table class="table table-striped table-bordered table-hover table-responsive " style="overflow: auto;">
                <thead>
                    <tr>
                        <th class="">Funcionario </th>
                        <th >teste </th>
                        <th>teste </th>
                        
                        <?php foreach($this->view->dataRange as $data){?>
                            <th> <?php echo $data ?> </th>
                        <?php }?>

                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td class="headcol"> bruno vicente do nascimento</td>
                        <td > 10</td>
                        <td> 10</td>
                        <td> 01</td>
                        <td> 10</td>
                        <td> 10</td>
                        <td> 10</td>
                        <td> 10</td>
                        <td> 10</td>
                        <td> 10</td>
                        <td> 10</td>
                        <td> 10</td>

                    </tr>
                    <tr>
                        <td class="headcol"> bruno vicente do nascimento</td>
                        <td > 10</td>
                        <td> 10</td>
                        <td> 10</td>
                        <td> 10</td>
                        <td> 10</td>
                        <td> 10</td>
                        <td> 10</td>                        
                    </tr>
                    <tr>
                        <td class="headcol"> bruno vicente do nascimento</td>
                        <td > 10</td>
                        <td> 10</td>
                        <td> 01</td>
                        <td> 10</td>
                        <td> 10</td>
                        <td> 10</td>
                        <td> 10</td>
                        <td> 10</td>
                        <td> 10</td>
                        <td> 10</td>
                        <td> 10</td>

                    </tr>
                    <tr>
                        <td class="headcol"> bruno vicente do nascimento</td>
                        <td > 10</td>
                        <td> 10</td>
                        <td> 01</td>
                        <td> 10</td>
                        <td> 10</td>
                        <td> 10</td>
                        <td> 10</td>
                        <td> 10</td>
                        <td> 10</td>
                        <td> 10</td>
                        <td> 10</td>

                    </tr>
                    <tr>
                        <td class="headcol"> bruno vicente do nascimento</td>
                        <td > 10</td>
                        <td> 10</td>
                        <td> 01</td>
                        <td> 10</td>
                        <td> 10</td>
                        <td> 10</td>
                        <td> 10</td>
                        <td> 10</td>
                        <td> 10</td>
                        <td> 10</td>
                        <td> 10</td>

                    </tr>
                    
                </tbody>
                
            </table>

        </div>
    </div>

</div>