<div class="container " >
            <!-- Top Navigation -->

        <div>
        <h1 class="text-center text">Horas concluídas <h1>
        </div>            
			
			<div class="component">
				
				<table class="overflow-y">
					<thead>
						<tr>
                            <th>Funcionario</th>
                            <?php foreach($this->view->dataRange as $data) {?>
                                <th <?php if(in_array($data, $this->view->fds)){echo "class=bg-info"; } ?>   > 
                                <?php echo $data; 

                               //echo $data->format('w') % 6 ? 'Não é fim de semana' : 'é fim de semana';

                                ?> </th>
                            <?php } ?>
                            
						</tr>
					</thead>
					<tbody>
                    <?php foreach($this->view->resultadoMensal as $rmensal){?>
                                <tr>
  
                                  <?php  $cont = 0;
                                    //print_r($rmensal);
                                    foreach($rmensal as $dados){
                                        if(!$dados){
                                            ?> <td <?php if(in_array($cont, $this->view->fds)){echo "class=bg-info"; } ?> >
                                                <?php echo 0; ?>
                                             </td> <?php
                                        }else{
                                            if($cont == 0){
                                                ?> <th>
                                                 <?php echo $dados ?>
                                                 </th> <?php
                                            }else{
                                            ?> <td <?php if(in_array($cont, $this->view->fds)){echo "class=bg-info"; } ?>> 
                                                <?php echo $dados ?></td>
                                             <?php
                                            }
                                        }
                                       // echo $cont;
                                        $cont ++;
                                    } //echo 'tamanho for:' . $cont . '</br>';
                              ?>
                              </tr>      
                           <?PHP }?>

                        
					</tbody>
				</table>
		
			</div>


		</div><!-- /container -->