<div class="container-fluid bg-light" style=" height: 100%; "   >

    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">

            <div class="card" style="margin: 5px;">
                <div class="card-header bg-info text-white">
                    SUGERIR EDIÇÃO
                </div>
                <div class="card-body">

                    <form name="editaveis" action="/editaveis" method='POST'>
                        <div class="form-row">
                            <div class="form-group col-7">
                                <label for="inputState">Numero do chamado</label>
                                <input type="text" class="form-control bg-light" required id="chamado_editavel" name="chamado_editavel"
                                    placeholder="numero do chamado">

                            </div>
                            <div class="form-group col-2">
                                <label for="inputState"> </br></label>
                                <button type="submit" class=" btn-info btn-sm btn-block">pesquisar</button>
                            </div>
                            
                        </div>
                    </form>

                </div>
            </div>

        </div>


    </div>


<div class="row " style=" padding: 8px; " >
<!-- <div class="col-1"></div> -->
            <div class="col-12">
               
                <div class="card">
                    <div class="card-header">
                        chamados encontrados
                    </div>
                    <div class="card-body">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                <th scope="col">chamado / ID</th>
                                <th scope="col">funcionario</th>
                                <th scope="col">Cliente</th>
                                <th scope="col">status</th>
                                <th scope="col">Atividade</th>
                                <th scope="col">data inicial</th>
                                <th scope="col">Duração</th>
                                <th scope="col">Autorizar</th>

                                </tr>
                            </thead>
                            <tbody>
                            <?php foreach($this->view->editaPorChamado as $chamado){?>
                        <form name="edt" id="edt" method="POST" action="/editaveis/Pendentes  ">    
                            <tr  >
                            <input type="text" value="<?php echo $chamado['Id'] ?>" style="display:none;" class="form-control bg-light" id="id_edt" readonly  name="id_edt">
                                <td  > <?php echo $chamado['num_chamado']; ?> </td>
                                <td><?php echo $chamado['nome']; ?></td>
                                <td><?php echo $chamado['cliente']; ?></td>
                                <td><?php echo $chamado['status']; ?></td>
                                <td> <?php echo $chamado['atividade']; ?></td>
                                <td> <?php echo $chamado['Data_inicial']; ?></td>
                                <td> <?php echo $chamado['duracao']; ?></td>
                            <td> <button type="submit" class="btn-success" id="" >Autorizar edição</button> </td>

                            </tr>
                            <?php } ?>
                        </form>
                            </tbody>
                            <tfoot>
                        <tr>
                            <th class="th-sm">
                            </th>
                            <th class="th-sm">
                            </th>
                            <th class="th-sm">
                            </th>
                            <th class="th-sm">
                            </th>
                            <th class="th-sm">
                            </th>
                            <th class="th-sm">
                            </th>
                            <th class="th-sm">
                            </th>
                            <th class="th-sm">
                            </th>
 

                        </tr>
                    </tfoot>
                        </table>
                    </div>
                </div>
                        
            </div>

<?php
if (empty($this->view->editaPorChamado) and ($this->view->postEdita == true)){
    echo "<h2> Não foi possivel localizar este apontamento <h2>";
}?>
    

    
</div>



<!-- fim cards -->







</div>