<div class="container-fluid bg-light"  style="padding:10px;">
    <!-- <div class="formulario"> -->
        <div class="card">
            <form>
                <div class="col-2"></div>

                <div class="form-row align-items-center">
                <div class="col-3">
                    <label class="sr-only" for="inlineFormInput">Name</label>
                    <input type="date" class="form-control mb-2" id="inlineFormInput" placeholder="Jane Doe">
                </div>
                <div class="col-3">
                    <label class="sr-only" for="inlineFormInputGroup">Username</label>
                    <div class="input-group mb-2">
                    <div class="input-group-prepend">
                    </div>
                    <input type="date" class="form-control" id="inlineFormInputGroup" placeholder="Username">
                    </div>
                </div>
                <div class="col-1">
                    <button type="submit" class="btn btn-info sm-1">Consultar</button>
                </div>
                </div>
            </form>
        </div>
    <!-- </div> -->

</form>
    <div class="card table-responsive " style="padding:10px; margin:3px">
         <!-- <div class="row">
             <div id="tes" class="col-12">


             </div>
        </div> -->

        <table id="historico" class="table table-striped table-bordered display " style="width:100%">
            <thead>
                <tr>
                    <th class="th-sm">N° chamado
                    </th>
                    <th class="th-sm">cliente
                    </th>
                    <th class="th-sm">tipo Atividade
                    </th>
                    <th class="th-sm">Atividade
                    </th>
                    <th class="th-sm">Data inicial
                    </th>
                    <th class="th-sm">Data final
                    </th>
                    <th class="th-sm">Tipo de hora
                    </th>
                    <th class="th-sm">Duracão
                    </th>
                </tr>

            </thead>
            <tbody>
                <?php foreach($this->view->todosApontamentos as $aponta){?>
                <tr>
                    <td> <?php echo $aponta['num_chamado']; ?> </td>
                    <td><?php echo $aponta['cliente']; ?></td>
                    <td><?php echo $aponta['tipo_atividade']; ?></td>
                    <td> <?php echo $aponta['atividade']; ?></td>
                    <td><?php echo $aponta['Data_inicial']; ?></td>
                    <td><?php echo $aponta['Data_final']; ?></td>
                    <td><?php echo $aponta['tipo_hora']; ?></td>
                    <td> <?php echo $aponta['duracao']; ?></td>
                </tr>
                <?php }?>
            </tbody>
            <tfoot>
                <tr>
                    <th class="th-sm">N° chamado
                    </th>
                    <th class="th-sm">cliente
                    </th>
                    <th class="th-sm">tipo Atividade
                    </th>
                    <th class="th-sm">Atividade
                    </th>
                    <th class="th-sm">Data inicial
                    </th>
                    <th class="th-sm">Data final
                    </th>
                    <th class="th-sm">Tipo de hora
                    </th>
                    <th class="th-sm">Duracão
                    </th>
                </tr>
            </tfoot>
        </table>

        <!-- </div> -->
    <!-- </div> -->
    </div>
    </div>
