<div class="container-fluid bg-light"  style="padding:10px;">
    <!-- <div class="formulario"> -->
    <div class="row">
        <div class="col-12">
        <div class="card">
            <div class="card-body">
            <form name="consultaIntervalo" action='/historico' method="POST">

                <div class="form-row align-items-center">
                <div class="col-1"></div>
                    <div class="col-3">
                        <label class="" for="">Data Inicial</label>
                        <input type="date" class="form-control bg-light" id="" name="dataInicio" >
                    </div>

                    <div class="col-3">
                        <label class="" for="">Data final</label>
                        <!-- <div class="input-group-prepend"> -->
                        <input type="date" class="form-control bg-light" id="" name="dataFim" >
                        <!-- </div> -->
                    </div>
                    
                    <div class="col-1">
                        <label class="" for=""></label>
                        <button type="submit" class="btn btn-info sm-1">Consultar</button>
                    </div>
                
                </div>
                <div class="form-row align-items-center">
                            <p> <a href="/historico"> clique aqui para limpar filtros </a> </p>
                </div>
       

            </div>
        </div>
        
        </div>


        <!-- <div class="col-4">
        <div class="card">
            <div class="card-body">
            <form>
                    <div class="form-group">
                        <label for="formGroupExampleInput">teste </label>
                        <input type="text" class="form-control" id="" placeholder="">
                    </div>
                    <div class="form-group">
                        <label for="formGroupExampleInput2">teste</label>
                        <input type="text" class="form-control" id="" placeholder="">
                    </div>
             </form>
        </div>


            </div>
        </div> -->

        </div>


        
    <!-- </div> -->
    <div class="card table-responsive " style="padding:10px; margin:3px">
         <!-- <div class="row">
             <div id="tes" class="col-12">


             </div>
        </div> -->

        <table id="historico" class="table table-striped table-bordered display " style="width:100%">
            <thead>
                <tr>
                    <th class="th-sm">N° chamado
                    </th>
                    <th class="th-sm">cliente
                    </th>
                    <th class="th-sm">tipo Atividade
                    </th>
                    <th class="th-sm">Atividade
                    </th>
                    <th class="th-sm">Data inicial
                    </th>
                    <th class="th-sm">Data final
                    </th>
                    <th class="th-sm">Tipo de hora
                    </th>
                    <th class="th-sm">Duracão
                    </th>


                </tr>

            </thead>
            <tbody>
                <?php foreach($this->view->todosApontamentos as $aponta){?>
                <tr <?php if($aponta['FK_status_Id']=='1'){ echo "";} ?>>
                    <td> <?php echo $aponta['num_chamado']; ?> </td>
                    <td><?php echo $aponta['cliente']; ?></td>
                    <td><?php echo $aponta['tipo_atividade']; ?></td>
                    <td> <?php echo $aponta['atividade']; ?></td>
                    <td><?php echo $aponta['Data_inicial']; ?></td>
                    <td><?php echo $aponta['Data_final']; ?></td>
                    <td><?php echo $aponta['tipo_hora']; ?></td>
                    <td> <?php echo $aponta['duracao']; ?></td>
                </tr>
                <?php }?>
            </tbody>
            <tfoot>
                <tr>
                    <th class="th-sm">N° chamado
                    </th>
                    <th class="th-sm">cliente
                    </th>
                    <th class="th-sm">tipo Atividade
                    </th>
                    <th class="th-sm">Atividade
                    </th>
                    <th class="th-sm">Data inicial
                    </th>
                    <th class="th-sm">Data final
                    </th>
                    <th class="th-sm">Tipo de hora
                    </th>
                    <th class="th-sm">Duracão
                    </th>
                </tr>
            </tfoot>
        </table>

        <!-- </div> -->
    <!-- </div> -->
    <!-- </div> -->
</div>
