<div class="container-fluid bg-light">

<div class="row">
        <div class="col-2"></div>
        <div class="col-7">

            <div class="card">
                <div class="card-header">
                    VERIFICANDO APONTAMENTOS
                </div>
                <div class="card-body">

                    <form name="pendentes" action="/pendentes" method='POST'>
                        <div class="form-row">
                            <div class="form-group col-7">
                                <label for="inputState">Funcionario</label>
                                <select name="funcionario" class="form-control">
                                <?php ;foreach($this->view->meusFuncionario as $func ){?>
                                <option value="<?php echo $func['id'] ?>"> <?php echo $func['nome']; ?> </option>
                           <?php };?>
                                </select>
                            </div>
                            <div class="form-group col-2">
                            <label for="inputState"> </br></label>
                                <button type="submit" class=" btn-primary btn-sm btn-block">pesquisar</button>
                            </div>
                            <div class="form-group col-2">
                            <label for="inputState"> </br></label>
                                <button type="button" class=" btn-danger btn-sm  btn-block"><a href="/pendentes" class="text-white">Limpar filtro </a></button>
                            </div>
                        </div>
                    </form>

                </div>
            </div>

        </div>


    </div>


    <div class="row" style="padding-top:10px; overflow: auto; height: 100%; " >
        <div class="col-12">
            <table class="table table-striped table-bordered display tableFixHead " id="apontamentosPendentes" name="apontamentosPendentes">
                <thead>
                    <tr id="1">
                        <th class="th-sm"> Nome funcionario
                        </th>
                        <th class="th-sm">departamento
                        </th>
                        <th class="th-sm">cliente
                        </th>
                        <th class="th-sm">numero chamado
                        </th>
                        <th class="th-sm">data inicia
                        </th>
                        <th class="th-sm">Duracão
                        </th>
                        <th class="th-sm">
                        <button class="btn-sm btn-primary" >marcar</button>
                        
                        </th>


                    </tr>
                </thead>
                <tbody>
                    
                    <tr>
                        <td style="display:none;"></td>

                        <td>shtsr</td>
                        <td>GRG</td>
                        <td>GR</td>
                        <td>GRG</td>
                        <td>GRG</td>
                        <td>GRG</td>
                        <td style="text-align:center;">
                        <input type="checkbox" aria-label="Checkbox for following text input">
                        </td>
                    </tr>
                    <tr>

                       <td style="display:none;"></td>
                        <td>shtsr</td>
                        <td>GRG</td>
                        <td>GR</td>
                        <td>GRG</td>
                        <td>GRG</td>
                        <td>GRG</td>
                        <td style="text-align:center;">
                            <button class="btn-sm btn-success" data-toggle="modal" data-target="#myModal" contenteditable="false">Edit</button>
                            <button class="btn-sm btn-success" data-toggle="modal" data-target="#myModal" contenteditable="false">Edit</button>

                        </td>
                    </tr>
                    <tr>
                        <td style="display:none;"></td>

                        <td>shtsr</td>
                        <td>GRG</td>
                        <td>GR</td>
                        <td>GRG</td>
                        <td>GRG</td>
                        <td>GRG</td>
                        <td style="text-align:center;">
                            <button class="btn-sm btn-success" data-toggle="modal" data-target="#myModal" contenteditable="false">Edit</button>
                        </td>
                    </tr>
                    <tr>

                       <td style="display:none;"></td>
                        <td>shtsr</td>
                        <td>GRG</td>
                        <td>GR</td>
                        <td>GRG</td>
                        <td>GRG</td>
                        <td>GRG</td>
                        <td style="text-align:center;">
                            <button class="btn-sm btn-success" data-toggle="modal" data-target="#myModal" contenteditable="false">Edit</button>
                        </td>
                    </tr>
                    <tr>
                        <td style="display:none;"></td>
                        <td>shtsr</td>
                        <td>GRG</td>
                        <td>GR</td>
                        <td>GRG</td>
                        <td>GRG</td>
                        <td>GRG</td>
                        <td style="text-align:center;">
                            <button class="btn-sm btn-success" data-toggle="modal" data-target="#myModal" contenteditable="false">Edit</button>
                        </td>
                        </tr>
                        <tr>

                        <td style="display:none;"></td>
                        <td>shtsr</td>
                        <td>GRG</td>
                        <td>GR</td>
                        <td>GRG</td>
                        <td>GRG</td>
                        <td>GRG</td>
                        <td style="text-align:center;">
                            <button class="btn-sm btn-success" data-toggle="modal" data-target="#myModal" contenteditable="false">Edit</button>
                        </td>
                        </tr>
                        <tr>
                        <td style="display:none;"></td>
                        <td>shtsr</td>
                        <td>GRG</td>
                        <td>GR</td>
                        <td>GRG</td>
                        <td>GRG</td>
                        <td>GRG</td>
                        <td style="text-align:center;">
                            <button class="btn-sm btn-success" data-toggle="modal" data-target="#myModal" contenteditable="false">Edit</button>
                        </td>
                        </tr>
                        <tr>

                        <td style="display:none;"></td>
                        <td>shtsr</td>
                        <td>GRG</td>
                        <td>GR</td>
                        <td>GRG</td>
                        <td>GRG</td>
                        <td>GRG</td>
                        <td style="text-align:center;">
                            <button class="btn-sm btn-success" data-toggle="modal" data-target="#myModal" contenteditable="false">Edit</button>
                        </td>
                        </tr>
                        <tr>
                        <td style="display:none;"></td>
                        <td>shtsr</td>
                        <td>GRG</td>
                        <td>GR</td>
                        <td>GRG</td>
                        <td>GRG</td>
                        <td>GRG</td>
                        <td style="text-align:center;">
                            <button class="btn-sm btn-success" data-toggle="modal" data-target="#myModal" contenteditable="false">Edit</button>
                        </td>
                        </tr>
                        <tr>

                        <td style="display:none;"></td>
                        <td>shtsr</td>
                        <td>GRG</td>
                        <td>GR</td>
                        <td>GRG</td>
                        <td>GRG</td>
                        <td>GRG</td>
                        <td style="text-align:center;">
                            <button class="btn-sm btn-success" data-toggle="modal" data-target="#myModal" contenteditable="false">Edit</button>
                        </td>
                        </tr>
                </tbody>
                <tfoot>
                    <tr>
                        <th class="th-sm">N° chamado
                        </th>
                        <th class="th-sm">cliente
                        </th>
                        <th class="th-sm">Atividade
                        </th>
                        <th class="th-sm">Data inicial
                        </th>
                        <th class="th-sm">Tipo de hora
                        </th>
                        <th class="th-sm">Duracão
                        </th>
                        <th class="th-sm">editar
                        </th>

                    </tr>
                </tfoot>
            </table>

        </div>
    </div>


</div>

<script type="text/javascript" charset="utf8" src="/js/scripts.js"></script>
